### ISSUE TITLE
Can't type pp!

### ISSUE THREAD

**Issue by haxbeats** [Jakeii/woocommerce-pesapal#11]
Hi! When I was trying to test the Pesapal plugin, and selected Mpesa, I get to step 4 and it says Enter pp for Account no. For some reason I can't type letters, just numbers. 
What do I do?
Also, Pesapal doesn´t work when I enable PayPal in the Checkout options. 
Best regards, Emma

**Comment by gachie** [comment]
Hi Haxbeats,

You are supposed to leave the account number blank.

For paypal, it does not support KES while pesapal supports KES by default. I think you need to play with the currencies.

**Comment by Jakeii** [comment]
This sounds solved? Feel free to reopen.
