### ISSUE TITLE
Not proceeding to the final step

### ISSUE THREAD

**Issue by DanMburu** [Jakeii/woocommerce-pesapal#6]
After payment, I'm still being redirected back to the payment page and the cart is not being reset.
The payment page: .../checkout/?order=390&key=wc_order_543ccded54195
Im using local host and the Demo Gateway

**Comment by peeteo** [comment]
Same thing happening to our eCommerce site...

**Comment by gachie** [comment]
Hi Guys, did you find a solution to this?

I fixed this by replacing 

`wp_redirect(add_query_arg('key', $order->order_key, add_query_arg('order', $order_id, get_permalink(woocommerce_get_page_id('thanks'))))); `

with

`wp_redirect(add_query_arg('key', $order->order_key, add_query_arg('order', $order_id, get_permalink(WC_Order::get_checkout_order_received_url()))));`

on line 411 in the file gateway.php

It works for me, lemme know if it works for you.

**Comment by ebookcental** [comment]
The fix is not working. It is redirecting indefinitely.

**Comment by gachie** [comment]
Sorry ebookcental. Can you share your pesapal plug in version and the gateway.php file so that i can have a look?

**Comment by maxwellmandela** [comment]
Sometimes it's mixed content and you don't get chrome allowing http when the page is served over https. It stopped mine before I figured it out. The demo loads an iframe over http. You could change this and perhaps get it continue to the next steps.

**Comment by Jakeii** [comment]
should be fixed in 2.1.0
