### ISSUE TITLE
Allow Passing currency based on what currency  the user has selected

### ISSUE THREAD

**Issue by mansonkibe** [Jakeii/woocommerce-pesapal#7]
From the plugin it takes the woo commerce currency that i have set in my settings but i want to extend it such that on my online shop a user can select the currency they want purchase with.

For instance my exchange rate i have set it 1 USD dollar to be kes 92 but when they chose Mpesa then the two values will differ. Is it possible to pass the kind of currency my customer user is using to maintain transparency of the currency conversion

It would be a great feature that will make this plugin great for East Africa E commerce shops

**Comment by Jakeii** [comment]
Sorry this didn't get a reply, there are other plugins that can do this for you however!
