### ISSUE TITLE
Problem: signature_invalid | Advice: > | 

### ISSUE THREAD

**Issue by sondh0021** [Jakeii/woocommerce-pesapal#8]
Hi,

When i reach the checkout page on the wordpress site, i get this error.

"Problem: signature_invalid | Advice: > | "

Why would it be giving me this error.

**Comment by Jakeii** [comment]
Make sure your API keys are perfectly correct

**Comment by bahiirwa** [comment]
@Jakeii That answer is precise. Please close comment. This has not been updates in years.
