### ISSUE TITLE
Problem: parameter_rejected | Advice: invalid_value_amount_exceeds_limit> oauth_parameters_rejected | 20000

### ISSUE THREAD

**Issue by mawioo** [Jakeii/woocommerce-pesapal#9]
Hi, Im having this error come up.. could you please guide me on a way to solve the issue

**Comment by Jakeii** [comment]
Check your currency, you are charging 20000, are you charging USD or KSH.

**Comment by mawioo** [comment]
What can I do to fix this.. Im charging KSH and this issue is persisting.. I havent found a way around it yet.
<img width="702" alt="screen shot 2016-02-16 at 11 44 45 am" src="https://cloud.githubusercontent.com/assets/16877299/13071167/c55275fa-d4a2-11e5-9f7e-d485a07a2eb5.png">

**Comment by Jakeii** [comment]
Make sure the currency code is KES and not USD, I see you have changed the
symbol, that does not necessarily mean that the currency has changed.

**Comment by mawioo** [comment]
I notice that My currencies are different from the check out page and what comes back after placing the order. What would cause this. and how do i go around it. Screenshot from one page to the next after placing the order.
<img width="745" alt="screen shot 2016-02-18 at 3 00 28 am" src="https://cloud.githubusercontent.com/assets/16877299/13129289/22080af8-d5ed-11e5-8238-9c17185364d8.png">
<img width="711" alt="screen shot 2016-02-18 at 3 00 49 am" src="https://cloud.githubusercontent.com/assets/16877299/13129290/220a5718-d5ed-11e5-9d70-a4b7ba7b856a.png">

**Comment by mawioo** [comment]
//Woocommerce doesn't have KSh by default so add it if not already added
  add_filter( 'woocommerce_currencies', 'add_kenya_shilling' );

  function add_kenya_shilling( $currencies ) {
    if(!isset($currencies['KES'])||!isset($currencies['KES'])){
       $currencies['KES'] = __( 'Kenyan Shilling', 'woocommerce' );
       
       return $currencies;
      }
  }

  add_filter('woocommerce_currency_symbol', 'add_kenya_shilling_symbol', 10, 2);
  function add_kenya_shilling_symbol( $currency_symbol, $currency ) {
     switch( $currency ) {
        case 'KES': $currency_symbol = 'KSh'; break;
     }
     return $currency_symbol;
  }
How do you structure this on your donation page? I switched the currecies to KES and  $currency_symbol to KSh/KES,/=

Still giving me the above error

**Comment by mawioo** [comment]
I figured it out. It works for me now.. Thanks
